# Generated by Django 3.1.5 on 2021-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_master',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=20)),
                ('bookprice', models.IntegerField()),
            ],
        ),
    ]
